### ISSUE TITLE
Checkout flow bug

### ISSUE THREAD

**Issue by IvanAnishchuk** [farhackxyz/farhack#12]
There seems to be a bug. Can someone test and fix it please so I can pay? (Or I could ask one of my junior hackers.)

![image](https://github.com/user-attachments/assets/3f4a8668-88bc-464e-a5cf-8546d155b389)

**Comment by dylsteck** [comment]
Thanks for making this issue @IvanAnishchuk, I'm happy to fix this and get it resolved ASAP for you!

Is there any chance you'd be able to tell me what sort of computer/browser you're using and if you have the Coinbase Wallet extension downloaded?(would be helpful for debugging)

**Comment by IvanAnishchuk** [comment]
Linux Firefox and chrome (chrome didn't even connect), tried mobile as well. No extension, no.

**Comment by dylsteck** [comment]
Gotcha, looking into this and will get back to you shortly to make sure this is resolved @IvanAnishchuk!

**Comment by IvanAnishchuk** [comment]
I tried w/ coinbase extension enabled as well with about the same result. Let me know if you need any more details

![image](https://github.com/user-attachments/assets/377340f2-1e30-473a-97cf-01dd0e4ad08b)

response is
```
{
    "jsonrpc": "2.0",
    "id": 8,
    "error": {
        "code": -32604,
        "message": "this request method is not supported"
    }
}
```

I have a team member asking questions about you guys, can you ping me in some DM maybe? Telegram or discord perhaps.

**Comment by IvanAnishchuk** [comment]
Ok, I managed to pay, this issue probably still need to be fixed (and maybe support other wallets?) thanks, looking forward to SG events.

**Comment by dylsteck** [comment]
Awesome, thanks so much and we look forward to having you @IvanAnishchuk! Separately we have an active ticket for this internally and I'll close this issue once we have it resolved in our next release.
